import type { Exercise } from '@/domain/exercises'

export const exercisesMock: Exercise[] = [
  { id: 'shoulder-mobility', kind: 'therapeutic', anatomicalStructureId: 'shoulder', name: 'Mobilidade de ombro', slug: 'mobilidade-de-ombro', description: 'Movimentos suaves para a articulação do ombro.', instructions: 'Eleve o braço lentamente até o limite confortável.', youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', active: true, createdAt: '2026-03-01T12:00:00.000Z', updatedAt: '2026-03-01T12:00:00.000Z' },
  { id: 'shoulder-evaluation', kind: 'evaluation', anatomicalStructureId: 'shoulder', name: 'Avaliação de mobilidade do ombro', slug: 'avaliacao-mobilidade-ombro', description: 'Movimento guiado para avaliar desconforto no ombro.', instructions: 'Eleve o braço lentamente e observe a dor.', youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', active: true, createdAt: '2026-03-01T13:00:00.000Z', updatedAt: '2026-03-01T13:00:00.000Z' },
  { id: 'knee-strengthening', kind: 'therapeutic', anatomicalStructureId: 'knee', name: 'Fortalecimento de joelho', slug: 'fortalecimento-de-joelho', description: 'Exercício funcional para o joelho.', instructions: 'Realize flexões curtas com postura controlada.', active: true, createdAt: '2026-03-02T12:00:00.000Z', updatedAt: '2026-03-02T12:00:00.000Z' },
  { id: 'knee-evaluation', kind: 'evaluation', anatomicalStructureId: 'knee', name: 'Avaliação de mobilidade do joelho', slug: 'avaliacao-mobilidade-joelho', description: 'Movimento guiado para avaliar desconforto no joelho.', instructions: 'Flexione o joelho lentamente e observe a dor.', active: true, createdAt: '2026-03-02T13:00:00.000Z', updatedAt: '2026-03-02T13:00:00.000Z' },
  { id: 'ankle-mobility', kind: 'therapeutic', anatomicalStructureId: 'ankle', name: 'Mobilidade de tornozelo', slug: 'mobilidade-de-tornozelo', description: 'Movimentos suaves para o tornozelo.', instructions: 'Faça círculos com o pé dentro do limite confortável.', active: true, createdAt: '2026-03-03T12:00:00.000Z', updatedAt: '2026-03-03T12:00:00.000Z' },
]
