import type { AnatomicalStructure } from '@/domain/anatomical-structures'

export const anatomicalStructuresMock: AnatomicalStructure[] = [
  { id: 'shoulder', bodyRegionId: 'upper-limb', name: 'Ombro', slug: 'ombro', description: 'Articulação que conecta o membro superior ao tronco.', active: true, mapPlacements: [{ face: 'anterior', side: 'left', left: '18%', top: '31%' }, { face: 'anterior', side: 'right', left: '32%', top: '31%' }, { face: 'posterior', side: 'left', left: '68%', top: '31%' }, { face: 'posterior', side: 'right', left: '82%', top: '31%' }], createdAt: '2026-02-01T12:00:00.000Z', updatedAt: '2026-02-01T12:00:00.000Z' },
  { id: 'elbow', bodyRegionId: 'upper-limb', name: 'Cotovelo', slug: 'cotovelo', description: 'Articulação intermediária do membro superior.', active: true, mapPlacements: [{ face: 'anterior', side: 'left', left: '15%', top: '44%' }, { face: 'anterior', side: 'right', left: '35%', top: '44%' }, { face: 'posterior', side: 'left', left: '65%', top: '44%' }, { face: 'posterior', side: 'right', left: '85%', top: '44%' }], createdAt: '2026-02-02T12:00:00.000Z', updatedAt: '2026-02-02T12:00:00.000Z' },
  { id: 'knee', bodyRegionId: 'lower-limb', name: 'Joelho', slug: 'joelho', description: 'Articulação entre a coxa e a perna.', active: true, mapPlacements: [{ face: 'anterior', side: 'left', left: '22%', top: '72%' }, { face: 'anterior', side: 'right', left: '28%', top: '72%' }, { face: 'posterior', side: 'left', left: '72%', top: '72%' }, { face: 'posterior', side: 'right', left: '78%', top: '72%' }], createdAt: '2026-02-03T12:00:00.000Z', updatedAt: '2026-02-03T12:00:00.000Z' },
  { id: 'gluteus', bodyRegionId: 'lower-limb', name: 'Glúteo', slug: 'gluteo', description: 'Grupo muscular da região posterior do quadril.', active: true, mapPlacements: [{ face: 'posterior', side: 'left', left: '68%', top: '57%' }, { face: 'posterior', side: 'right', left: '82%', top: '57%' }], createdAt: '2026-02-04T12:00:00.000Z', updatedAt: '2026-02-04T12:00:00.000Z' },
  { id: 'ankle', bodyRegionId: 'lower-limb', name: 'Tornozelo', slug: 'tornozelo', description: 'Articulação entre a perna e o pé.', active: true, mapPlacements: [{ face: 'anterior', side: 'left', left: '22%', top: '91%' }, { face: 'anterior', side: 'right', left: '28%', top: '91%' }, { face: 'posterior', side: 'left', left: '72%', top: '91%' }, { face: 'posterior', side: 'right', left: '78%', top: '91%' }], createdAt: '2026-02-05T12:00:00.000Z', updatedAt: '2026-02-05T12:00:00.000Z' },
]
